version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'your_username'
      POSTGRES_PASSWORD: 'your_password'
      POSTGRES_DB: 'charging_station'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
